baseURL = "http://localhost:1313/"
languageCode = "en-us"
title = "VL-PYNET-AI"
# Stelle sicher, dass dies dem Namen des Themes entspricht
description = "use my newly developed tool to take your real time image generation one step further"
date = 2024-10-10T16:45:42+02:00
weight = 20
draft = false
bref = ""
toc = true